---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: /:title ## disables post output
timezone: null
lsi: false
markdown: kramdown


### content configuration ###
title:       "George K. Thiruvathukal"
keywords:    "professor, writer, researcher, media, github, blog, single page"
description: "George K. Thiruvathukal's new Web Site"
source_link: "https://github.com/gkthiruvathukal/gkthiruvathukal.github.io"
favicon:     "img/favicon.ico"
touch_icon:  "img/apple-touch-icon.png"
google_analytics_key: UA-23507985-1 ## put YOUR key here to enable tracking! (blank to disable)


### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#f8f8f8'
  blue:      '#49a7e9'
  green:     '#9bcf2f'
  purple:    '#c869bf'
  orange:    '#fab125'
  turquoise: '#0fbfcf'
  pred:      '#ffb3ba'
  porange:   '#ffdfba'
  pyellow:   '#ffffba'
  pgreen:    '#baffc9'
  pblue:     '#bae1ff'


kramdown:
  auto_ids:  false

